services:
  - type: web
    name: hate-speech-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
