[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = false
fileWatcherType = "none"
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[logger]
level = "error"

[client]
caching = true
