# ===========================================
# CONFIGURACIÓN SECRETA PARA STREAMLIT CLOUD
# ===========================================

# Variables de entorno para Streamlit Community Cloud
# Estas se pueden configurar en el dashboard de Streamlit

[general]
# Configuración general
debug_mode = false
log_level = "INFO"

# Configuración de base de datos (opcional)
database_enabled = true
database_path = "hate_speech.db"

# Configuración de modelos
confidence_threshold = 0.5
max_evaluations = 10
improvement_threshold = 0.03

# APIs externas (opcional - configurar en Streamlit Cloud)
[apis]
google_perspective_api_key = ""
api_verve_key = ""
neutrino_api_key = ""
api_ninja_key = ""
